# Generated by Django 5.1.6 on 2025-03-24 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='cpfAluno',
            field=models.CharField(default=1, max_length=11),
            preserve_default=False,
        ),
    ]
