# Generated by Django 5.1.6 on 2025-02-17 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0001_initial'),
        ('professores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiposDeUsuario',
            fields=[
                ('idTipo', models.IntegerField(primary_key=True, serialize=False)),
                ('nomeTipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loginUsuario', models.CharField(max_length=100)),
                ('senhaUsuario', models.CharField(max_length=100)),
                ('idAluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alunos.aluno')),
                ('idProfessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professores.professor')),
                ('idTipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginpage.tiposdeusuario')),
            ],
        ),
    ]
