# Generated by Django 5.1.6 on 2025-02-17 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0001_initial'),
        ('professores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Musculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeMusculo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeExercicio', models.CharField(max_length=100)),
                ('musculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.musculo')),
            ],
        ),
        migrations.CreateModel(
            name='PlanoDeTreino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataInicio', models.DateField()),
                ('dataFim', models.DateField()),
                ('idAluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.aluno')),
                ('idProfessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professores.professor')),
            ],
        ),
        migrations.CreateModel(
            name='Treino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diaDaSemana', models.IntegerField()),
                ('series', models.IntegerField()),
                ('repeticoes', models.IntegerField()),
                ('observacoes', models.TextField()),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.exercicio')),
                ('planoDeTreino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.planodetreino')),
            ],
        ),
    ]
