# Generated by Django 5.1.3 on 2025-03-30 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_planodetreino_datafim'),
        ('professores', '0003_remove_professor_cpfaluno_professor_nomeprofessor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planodetreino',
            name='idProfessor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='professores.professor'),
        ),
    ]
