# Generated by Django 5.1.6 on 2025-03-24 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='nomeProfessor',
        ),
        migrations.AddField(
            model_name='professor',
            name='cpfAluno',
            field=models.CharField(default=12345678912, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professor',
            name='cpfProfessor',
            field=models.CharField(default=12345678912, max_length=11),
            preserve_default=False,
        ),
    ]
