# Generated by Django 5.1.6 on 2025-03-24 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0002_remove_professor_nomeprofessor_professor_cpfaluno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='cpfAluno',
        ),
        migrations.AddField(
            model_name='professor',
            name='nomeProfessor',
            field=models.CharField(default='maria', max_length=100),
            preserve_default=False,
        ),
    ]
